### PR TITLE
Fixing crash

### PR DESCRIPTION
**Pull request by cantalupo555**

### CODE REVIEW

**Comment by buddyjojo** [comment]
Well I gave that just as a quick workaround. I'm going to leave that code in there and just remove the else statement just in case I ever want to add macos support back. And as for the uefi flashing, I already stated that doesn't work.

**Comment by cantalupo555** [comment]
> Well I gave that just as a quick workaround. I'm going to leave that code in there and just remove the else statement just in case I ever want to add macos support back. And as for the uefi flashing, I already stated that doesn't work.

So the problem is in this first line?

**Comment by cantalupo555** [comment]
It's not really definitive, however the script would be able to run:

image

**Comment by buddyjojo** [comment]
I already said, I'm working on the proper solution.

**Pull request closed without merging**
